### ISSUE TITLE
Generate the gene signatures for diabetes and heart disease

### ISSUE THREAD

**Issue by markziemann** [markziemann/gene_sig_commons#6]
Hi Aaron,
please take a look at what I have done with https://github.com/markziemann/gene_sig_commons/blob/master/epilepsy_de.Rmd 
which generates the gene signatures for our epilepsy contrasts. The results are found here: http://118.138.234.73/public/gene_sig_commons/
Could you have a go at creating an Rmd file called "diabetes_de.Rmd" which processes the diabetes related studies?
If you have doubts, we can work through it during our next meeting.
Cheers,
Mark

**Comment by aaronsk7** [comment]
Okay Mark, sounds good.
