### ISSUE TITLE
SARS contrasts with issues

### ISSUE THREAD

**Issue by hlek02** [markziemann/gene_sig_commons#9]
Issue with line 15 

SRP253279: high binding to the RBD of the S protein versus low binding to the RBD of the S protein (fragments A and B): high binding RBD; SRX7950378, SRX7950380: low binding RBD; SRX7950382, SRX7950384;

Error in apply(yy, 2, function(x) { : dim(X) must have a positive length

All other contrasts seem to be working fine.

**Comment by markziemann** [comment]
Have made an update to the functions and now it works fine :)
